### PR TITLE
Fix linking to libfortran on MacOS

### PR DESCRIPTION
**Pull request by jeroen**

### CODE REVIEW

**Review by eddelbuettel — APPROVED** [review]
That's better and more general than what I had sketched.

Good use of the existing 'hook' `install.lib.R` too!

**Comment by jeroen** [comment]
Actually doing it in the Makefile may be more elegant

**Comment by eddelbuettel** [comment]
> Actually doing it in the Makefile may be more elegant

No, reopen.  That is good.  And/or call your script from the `src/Makefile`.   You correctly take care of _both_ arguments to `install_name_tool`.

**Review by eddelbuettel — CHANGES_REQUESTED** [review]
It is missing the `install_name_tool` call for `libquadmath` though

**Review by eddelbuettel — APPROVED** [review]

**Comment by eddelbuettel** [comment]
Hm.  Now I force pushed this and thereby closed it.  Darn.  Might have been because I also (accidentally !!) pushed this as branch first.

**Comment by eddelbuettel** [comment]
And in doing so I appear to have clobbered the fork by @jeroen.  Hm.

**Pull request closed without merging**
