### PR TITLE
Feature/build26

### PR DESCRIPTION
**Pull request by christophsax**
Installs on Win (appveyor), Linux (travis) and Mac (my box). 

On the mac, I get the numerically identical results  for about 100 test runs as with build19, so everything seems to be fine.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Question if/when/how/ever we will adjust the old binaries away into v1.1.19.

**Comment by christophsax** [comment]
Oh, Census even have a [changelog](https://www.census.gov/srd/www/x13as/releaseNotes.html). Does not look problematic, but I will do some more checks with seasonal over the weekend, if we can wait that long with an update.

If we are putting it away, we are invalidating x13binary 0.1.1. So perhaps we should not put it away as long as x13binary 0.1.1 appears anywhere on CRAN (e.g. as an oldrel binary). At that point (in 1 month, 4 month?), we can be probably be confident that nobody still wants to install x13binary 0.1.1.

**Comment by eddelbuettel** [comment]
Yes, I was thinking thinking the same--proper deprecation with a longish timeout window.

**Comment by christophsax** [comment]
Did a few more checks with seasonal. Everything seems to be fine.
- [X] play with new version on win
- [X] check parsing of error msg
- [X] check some exotic functions (qs, fivebestmodels)
- [X] play with inspect

Also run x13binary on winbuilder, release and devel. I guess we are ready to go.

**Comment by eddelbuettel** [comment]
Good -- so I guess I just wrap this up as 0.1.2 ?

**Comment by christophsax** [comment]
Perfect!

**Comment by eddelbuettel** [comment]
Ok -- on its way.  Maybe should have made it clearer in the ChangeLog that it install 1.1.26.  Oh well.

**Comment by christophsax** [comment]
Thanks!

**Pull request merged**
