### PR TITLE
Fail hard and loud

### PR DESCRIPTION
**Pull request by krlmlr**
in default `./configure` script.

### CODE REVIEW

**Review by eddelbuettel — COMMENTED** [review]
Yes/no/maybe.

I am lukewarm on marginal PRs we did not ask for.  Yes, we all know 'pipefail' is good.  Do a lot of shell configure scripts need it?  Not sure esp if the added crazyness of 'oh my god sh may be different from bash'.

So I appreciate the intent but if I may please do not go around altering every shell script you see in every repo of ours / mine.

**Comment by krlmlr** [comment]
You're welcome.

**Comment by krlmlr** [comment]
In this particular case `R CMD INSTALL` succeeded even if the download failed. I'd argue this is wrong, at the end of the day it's your call -- and ending the discussion is just a button click away. I don't care which, really.

**Review by eddelbuettel — APPROVED** [review]

**Comment by eddelbuettel** [comment]
Good point. What `R CMD ...` does is the right metric here, of course.  I'll keep that in mind for the other few shell-based `configure` scripts I have (_i.e._ not `autoconf` generated ones which may have this already in their usually 100+ kb size).

**Comment by eddelbuettel** [comment]
Do we know why CI now fails?

**Comment by eddelbuettel** [comment]
Checking out your branch and looking more closely:

```sh
edd@rob:~/git/x13binary(local/pr56)$ R CMD INSTALL x13binary_1.1.39-3.2.tar.gz 
* installing to library ‘/usr/local/lib/R/site-library’
* installing *source* package ‘x13binary’ ...
** using non-staged installation via StagedInstall field
./configure: 23: set: Illegal option -o pipefail
ERROR: configuration failed for package ‘x13binary’
* removing ‘/usr/local/lib/R/site-library/x13binary’
* restoring previous ‘/usr/local/lib/R/site-library/x13binary’
edd@rob:~/git/x13binary(local/pr56)$ 
```

I think this was a good idea but this uses `#!/bin/sh`.  So all we can do is `set -e`.

**Comment by krlmlr** [comment]
Good to know, thanks. `set -e` was the important part.

**Comment by eddelbuettel** [comment]
I actually did get Vienna (or, possibly, Oxford) to make me change from `#!/bin/bash` to `#!/bin/sh` in two or three repos such as this because, you know, maybe one day these scripts will run on another Mars Rover or so which may not have `bash`.   I think Kevin has the cleanest approach where `configure` is a `/bin/sh` one-liner sourcing a `bash` script from `tools/` ....

**Pull request merged**
