### PR TITLE
Build from source

### PR DESCRIPTION
**Pull request by christophsax**
Finally, something, mostly the work of @Antonov548 and @krlmlr.

Here, a version without the 'src -> tools' renaming, but at the price of my own (probably much worse) hack [here](https://github.com/christophsax/x13binary/blob/binary2/src/dummy.c), to avoid a warning about an empty `src` folder. Renaming to 'tools' is an alternative, but perhaps there are nicer solutions out there?

However, it seems to work. I ran the following successfully on all platforms:
```r
remotes::install_github("christophsax/x13binary", ref = "binary2")
```

Successful R CMD checks on:

Mac
- My M2
- GHA

Win
- Winbuilder
- Local machine
- (the checks for Win don't start on GHA, but this seems a GHA configuration issue, not a problem with the package)

Ubuntu
- GHA
- Ubuntu Server

There is the mac builder issue: For some reason, it compiles, but the resulting binaries seem to be Linux binaries.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Will give it a whirl (currently traveling) but at a high-level observation this is probably a new record:

image

Conceptually speaking is there a chance to have fewer than 971 files changed?

**Comment by christophsax** [comment]
There are 963 source files. How could this work without that many file changes?

**Comment by krlmlr** [comment]
We might be able to split into two PRs -- one that just adds the files without doing anything to them, and another that switches to building from source. But since we're only adding files, I wonder what the added value of that is.

**Comment by eddelbuettel** [comment]
> There are 963 source files. How could this work without that many file changes?

_If_ and when the 'how we build_ changes where to be able to separated it would make a small and more easily reviewable PR, to which potentially an update to (the somewhat more external Census) file could be split from.  Sometime it works this, maybe this time it doesn't.

Most projects review PRs at GH because the UI is good for small to medium change sets.  We have all been here many years, but I don't think I have been asked to review 971 files in one changeset.  As for `src` -> `tools` and `dummy.c` I understand better now (as this package is now an 'empty vessel for an external executable') so yes we could consider `tools` on the other hand having `src` also flags we have compilation...  No clear winner, and something a discussion in an issue, which we didn't really have, could have prepared for.   Anyway...

**Comment by eddelbuettel** [comment]
I checked the repo out and it is _much less scary now_:

```sh
edd@rob:~/git/x13binary-christoph-pr66(binary2)$ diff -qru --exclude .git --exclude "*tar.gz" ../x13binary .
Files ../x13binary/configure and ./configure differ
Files ../x13binary/configure.win and ./configure.win differ
Files ../x13binary/.github/workflows/ci.yaml and ./.github/workflows/ci.yaml differ
Files ../x13binary/.gitignore and ./.gitignore differ
Only in ../x13binary/inst/bin: x13ashtml
Only in ../x13binary/inst/tools: new
Files ../x13binary/R/checkX13binary.R and ./R/checkX13binary.R differ
Files ../x13binary/.Rbuildignore and ./.Rbuildignore differ
Only in .: src
edd@rob:~/git/x13binary-christoph-pr66(binary2)$ 
```

Those changes all look good.  The buld is in `src/`.

**Comment by eddelbuettel** [comment]
It seems to work perfectly fine -- very nice work.

**Comment by christophsax** [comment]
If you want me to change it from draft into a proper PR, please let me know. 

Any opinion on the `src -> tools` vs `dummy.c` debate? I can also PR the `src -> tools` version if you prefer.

**Comment by eddelbuettel** [comment]
You know I am really really torn.  "Because it compiles someting" having `src/` may make sense.  Yet "because it doesn't dynamically extend R" it also makes no sense.  So _maybe_ `tools/` really is better, plus an appropriate sentence in `DESCRIPTION` and its `SystemRequirements:`  ?

**Comment by christophsax** [comment]
Here is another PR, using the tools approach: https://github.com/x13org/x13binary/pull/67

**Comment by eddelbuettel** [comment]
Oh, in looking at #67 I had missed that it was a duplicate of / alternate for #66.  Can I suggest we close one (of your choosing) and carry on with the other?

**Pull request closed without merging**
