### PR TITLE
Bug/quote windows

### PR DESCRIPTION
**Pull request by christophsax**
this should settle the space issue (#32), the working directory issue (#28) and give a more verbose output when failing (#29).

### CODE REVIEW

**Comment by eddelbuettel** [comment]
I was never one to care much for appveyor and Windows CI testing, but one could argue that it is just what we need here now.  

I presume you already tossed it at win-builder?

**Comment by christophsax** [comment]
no, but will do.

**Comment by christophsax** [comment]
I am normally developing on the mac but test it on a win laptop, installing from Github. That's why I have so many commits here.

**Comment by eddelbuettel** [comment]
I write/edit on Linux, but often submit via ftp to win-builder before committing.  Very worst case I can even rely on a machine at work ... but that more or less requires being at work and staying late.

**Comment by eddelbuettel** [comment]
Sorry. Guess I should have merged that yesterday.

And ... are we ready for a 0.1.1 upload then?

**Comment by christophsax** [comment]
Yes, I think we are ready. Finally have a [confirmation](https://github.com/christophsax/seasonal/issues/146#issuecomment-181984430) that whitespaces in Win paths are working now. 

Still open is the UNC path issue #30, don't think we can do anything here. A fix in seasonal `.onLoad()` will suggest to set the path to X-13 manually if `x13binary::checkX13binary()` fails. Will update soon afterwards.

**Comment by eddelbuettel** [comment]
And we're live!  Thanks for all your work on this to make the Windoze side more stable and sane.

**Pull request merged**
