### PR TITLE
Feature/appveyor ci

### PR DESCRIPTION
**Pull request by christophsax**
seems to work fine…

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Nice. How long is the runtime for each appveyor test, approximately?

**Comment by christophsax** [comment]
Not sure. It may even be a bit faster than on travis. But it queues a bit longer. Perhaps.

**Comment by eddelbuettel** [comment]
URL?  I don't have an appveyor handle yet, I think...

**Comment by christophsax** [comment]
https://ci.appveyor.com/project/christophsax/x13binary

**Comment by eddelbuettel** [comment]
Two mins 54 seconds.  Not terrible.

**Comment by christophsax** [comment]
And it even measures the time it takes :-)

**Comment by eddelbuettel** [comment]
And _very freshly added_: https://travis-ci.org/eddelbuettel/gunsales/builds

The launchpad build of x13binary does not contain the binary; package builds fine here.  I suspect they are simply sensible and disallow random binaries from external sites to be downloaded and packaged. 

So I [post-process in .travis.yml](https://github.com/eddelbuettel/gunsales/blob/master/.travis.yml#L37-L42). Which failed in take one, so let's see if I can bend this into shape...

**Comment by eddelbuettel** [comment]
And that took frigging forever.

I may 'replace' the `x13binary` with one I prepare locally, commit to x13prebuilt as well and then pull down.  Would that be ok with you?

**Comment by christophsax** [comment]
What I don't understand: Why can I use x13binary properly here with
seasonal?

https://travis-ci.org/christophsax/seasonal

**Comment by eddelbuettel** [comment]
Because you install from source. I do everything from r-cran-\* binaries, and built two [(over on launchpad)](https://launchpad.net/~edd/+archive/ubuntu/misc/+packages) to use.  It just so happens that the one for `x13binary` is defunct.

I have always used this older Travis approach because I dislike having to recompile frequently-used packages for each test.  That's just me ...

(The new scheme is fine, and easier.  But I like to exercise more control so ...  But today was tedious.)

**Pull request merged**
