### PR TITLE
Build from source (with sources in 'tools')

### PR DESCRIPTION
**Pull request by christophsax**
This should work on all platforms:
```r
remotes::install_github("christophsax/x13binary", ref = "binary")
```

Successful R CMD checks on:

Mac
- My M2
- GHA

Win
- Winbuilder
- Local machine
- (the checks for Win don't start on GHA, but this seems a GHA configuration issue, not a problem with the package)

Ubuntu
- GHA
- Ubuntu Server

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Updated my local checkout from your `binary2`  branch -- still looks good.  Any idea why appveyor fails when the other three pass?

Thanks to @krlmlr and @Antonov548 for updating all the CI and build scripts.  "It should always have worked like this" and it is really nice to actually see it work that way.

**Comment by christophsax** [comment]
I don't understand why appveyor fails. It tested it on win builder, so it should be fine in principle.

Note that the GHA check for windows is not configured correctly. The checkmark there doesn't tell us much.

**Comment by eddelbuettel** [comment]
I was wondering about Windows.   My r-ci.sh setup does not cover it methinks.  We may need a new yaml file this.

So maybe 'build also on Windows in CI' is the last one outstanding?  Can you good folks take a look?

**Comment by christophsax** [comment]
Thanks for the patience. Now with an additional workflow that uses r-lib/actions to perform the checks for Windows. I left the existing workflow unchanged; alternatively, the mac and Linux checks could be done with the same workflow.

Building on the `tools` folder approach as discussed in the previous PR. It looks less hacky to me than the dummy code in `src`.

I don't know how to deactivate the appveyor workflow, but I guess we don't need this anymore.

**Comment by eddelbuettel** [comment]
Yep -- I tend to use the same approach of adding yaml for supplementary actions.  As for 'un-hooking' appveyor hopefully removing the yaml file is enough. Else maybe we need to login the site?  Dunno.

**Review by eddelbuettel — APPROVED** [review]
This looks like it ready.  Great (and very patient) work.

**Pull request merged**
