### PR TITLE
x13path function to be imported by other pkg

### PR DESCRIPTION
**Pull request by christophsax**
So I would only import this function, and will not use `checkX13binary()` in seasonal.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
In principle that is good.  

But I think we need _someone_ to also check about the binary.  I.e. whether on Windows the file ends in `.exe` and/or all tests we think the x13binary package could/should do: maybe file size, executable mode, ability to run it (but leave fine-grained tests to seasonal -- or should those come over here?).  

So in essence a function building on this that asserts that the binary is _good to use_. Could return a `boolean`.  Users like seasonal could then call that quickly once in their `.onLoad()`.

What do you think?

**Comment by christophsax** [comment]
We still have `checkX13binary()` which does a basic ability-to-run test of x13binary. It currently returns a message if it works or fails otherwise. Can also extend it along your suggestions.

In seasonal, it makes more sense to run `checkX13()` (which basically hasn't been changed since the last CRAN version of seasonal), which more broadly checks the prerequisites of seasonal: If a manual `X13_PATH` has been set (perhaps, because you are on Solaris), it will test it as well. (We could also move this whole manually-setting-the-`X13_PATH` thing and its testing to x13binary, but this would be a lot of reshuffle and I don't see the benefit too well.)

I am a bit reluctant of doing an X-13 call during every startup of seasonal, as it takes around 0.2 sec. Is there a way to run `checkX13binary()` only after installation?

**Comment by eddelbuettel** [comment]
Can we break this discussion into subtopics, maybe different issue tickets.

What we still do **very wrong** right now is that we do not rely unit tests. I fell for that, and what was meant to be a half-hour check of the current code of gunsales, seasonal and x13binary turned into a three-hour debugging nightmare. My bad.

The upshot is that I simply no longer believer what you and I say :)   It is too easy to fall for 'it works' in a running (RStudio, say) session.  The only real test is unit-testing from cold starts as Travis does.  Only then will I believe whether we have Imports: or Depends: nailed.  _Because none of that is really needed just to test presence of a binary_.

As for testing on startup, my thinking is a little refined based on the experience with by now almost half a dozen packages:
- by default we should: "fail early, fail often".  
- seasonal is not all that useful without x13 so I think we should
- BUT we can add options() to a) skip tests and/or b) more/less verbose and/or war but don't die

etc pp.  To be discussed. 

Am I making sense?

(And no I am not grumpy. We made awesome strides with this in just a few days. I am really happy about it.  This has been an excellent collaboration so far, and we're not done yet :)

**Comment by christophsax** [comment]
Excellent, so let's see if I got what you are saying:
- I cleaned up the output of `checkX13binary()` to be more usable for seasonal in `onLoad()` (ok, this is probably not what you were saying :))
- As a unit test, or kind of, I added a check to `tests/simpleTest.R`. The difficult thing would be to have a test that shows that the check works correctly if x13binary is not working.
- Adjusted [seasonal](https://github.com/christophsax/seasonal/commit/948d953a7e6d690dab65c46c526abe7768070647) to run `checkX13binary()` on startup, and also added a [test](tests/test-all.R) there. This should fail right now, but work when `x13path()` is available.

**Comment by eddelbuettel** [comment]
Awesome.  

In order:
- Returning `bool` is probably best. Output to screen could be optional.
- Unit tests rock, and `tests/*.R` is the easiest way to get going. I know the Travis infrastructure pretty well so we can work on proper `.travis.yml` scripts relying in CRAN and/or GH
- Sweet. That sounds about right!

I am mostly incommunicado for the rest of today though.

**Comment by christophsax** [comment]
Cool. If travis tests work for seasonal, I will merge it down to master if ok for you. Will keep the x13download branch so existing code should still work.

Do you want `checkX13binary()` to return only TRUE or FALSE, and not contain `stop()`? Currently it gives a FALSE for non supported systems like Solaris and TRUE for Success, but it would stop on errors with the binary.

**Comment by eddelbuettel** [comment]
I can help with travis minutia and tuning, ie more relying of binary packages that load quickly.

As for the checker function, maybe silent by default and boolean by default is sensible?  How would you want an API to be?

**Comment by christophsax** [comment]
It’s rather slow for seasonal, but the numerical tests are taking also quite some time. But I think I can live well with that. Tests passed.

I am ok with the checker function as it is right now. Can also live with silent by default, but if you manually want to run the function at some time, you rather don’t want it to be silent?

**Comment by eddelbuettel** [comment]
When you say _taking some time_ you mean the Travis run (and setup/installation) takes time (and I can help with that).

Or do you mean that it takes a while because you added so many tests?   That we could control to :)

**Comment by christophsax** [comment]
It takes 133 s to reach the CRAN checks. And then it takes another 2 min for the tests, because I am running lots of X-13 examples.

E.g., [here](https://travis-ci.org/christophsax/seasonal/builds/100474552)

**Comment by eddelbuettel** [comment]
Yep: 
Line 428 is 45s for TeX which we don't need
Line 666 is 3s for Pandoc which we don't need (but then 3 sec ...)
Line 697 is 13s for devtools which I don't use
Line 856 is 28s for dependecies via devtools
I can possibly help you with that.  I do Travis the 'older school' way with more explicit apt-get install r-cran-*

The 2 mins of testing x13 is time well spent though.  And whether the rest matters when we have something that works is up for debate.  I can make it faster; does it really matter though?

**Comment by christophsax** [comment]
No, it doesn’t matter. Also, I probably need TeX for the pdf vignette. Let’s keep it as it is.

**Comment by eddelbuettel** [comment]
Sure. I am impatient and generally turn off vignette building at Travis.  But the other nice thing is that Travis does (or will ?) offer caching in some of the setups.  So some of these setup costs you only incur once (until things change).

**Pull request merged**
